[package]
name = "cli"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
colored = "1.5"
docopt = "0.8"
serde = "^1.0"
serde_derive = "^1.0"
trailer = { path = "../" }
ta = "0.1.0"
ta-lib-wrapper = "0.1.1"